apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tetronom-org-tls
spec:
  secretName: tetronom-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tetronom.org
  dnsNames:
    - tetronom.org
    - www.tetronom.org
